#!/usr/bin/env node

/**
 * Bundles each Lambda handler into a self-contained JS file using esbuild.
 * Output goes to dist/handlers/<name>/index.mjs — ready for CDK's Code.fromAsset.
 */

import { build } from 'esbuild';
import { readdirSync, statSync } from 'fs';
import path from 'path';

const HANDLERS_DIR = path.resolve('src/handlers/lambdas');
const OUT_DIR = path.resolve('dist/handlers');

// Each direct child folder of src/handlers/lambdas/ is a Lambda entry point.
let entries = [];
try {
  entries = readdirSync(HANDLERS_DIR).filter((name) => {
    const full = path.join(HANDLERS_DIR, name);
    return statSync(full).isDirectory();
  });
} catch {
  console.log(`No ${HANDLERS_DIR} directory yet — skipping build.`);
  process.exit(0);
}

if (entries.length === 0) {
  console.log('No handler directories found under src/handlers/lambdas/ — skipping build.');
  process.exit(0);
}

const entryPoints = entries
  .map((name) => {
    const index = path.join(HANDLERS_DIR, name, 'index.ts');
    try {
      statSync(index);
      return { name, entry: index };
    } catch {
      return null;
    }
  })
  .filter(Boolean);

if (entryPoints.length === 0) {
  console.log('No index.ts found in handler directories — skipping build.');
  process.exit(0);
}

await Promise.all(
  entryPoints.map(({ name, entry }) =>
    build({
      entryPoints: [entry],
      bundle: true,
      platform: 'node',
      target: 'node20',
      format: 'esm',
      outfile: path.join(OUT_DIR, name, 'index.mjs'),
      sourcemap: true,
      minify: false,
      external: ['@aws-sdk/*'],
      banner: {
        js: '// Auto-generated by build-lambdas.mjs — do not edit',
      },
    }).then(() => console.log(`  ✓ ${name}`)),
  ),
);

console.log(`\nBundled ${entryPoints.length} handler(s) into ${OUT_DIR}`);
